import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Image from "next/image";
import { ClerkProvider, UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

const navbar = [
  { name: "Home", url: "/" },
  { name: "Sign up", url: "/sign-up" },
  { name: "Messages", url: "/messages" },
  { name: "Sign In", url: "/sign-in" },
];

const navbar2 = [
  { name: "Today's Deal", url: "/todaysdeal" },
  { name: "Customer Service", url: "/customerservice" },
  { name: "Registry", url: "/registry" },
  { name: "Gift Cards", url: "/giftcards" },
];

interface NavbarProps {
  items: { name: string; url: string }[];
  className?: string;
}

export const metadata: Metadata = {
  title: "Green Market",
  description: "Generated by create next app",
};

const Navbar: React.FC<NavbarProps> = ({ items, className }) => (
  <ul className={`inline-flex gap-4 ${className}`}>
    {items.map((item, index) => (
      <li key={index}>
        <Link href={item.url} aria-label={item.name}>
          {item.name}
        </Link>
      </li>
    ))}
  </ul>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <nav className="relative z-10 flex items-center justify-between p-4 bg-slate-900">
          <div className="mx-auto">
            <Image
              src="/path-to-your-logo.png"
              width={125}
              height={40}
              alt="Logo"
              
            />
          </div>
          <div className="w-[600px] inline-flex gap-1">
            <Input type="search" aria-label="Search" />
            <Button variant="secondary" aria-label="Search">
              Search
            </Button>
          </div>
          <Navbar items={navbar} className="hidden sm:inline-flex gap-4 mx-auto text-xs text-zinc-100" />
          <div className="mx-auto">
            <Button variant="destructive" aria-label="My cart">
              My cart
            </Button>
          </div>
          <UserButton />
        </nav>
        <div className="sticky top-0 z-20 bg-slate-950 p-3">
          <Navbar items={navbar2} className="hidden sm:inline-flex gap-6 text-zinc-100 text-sm" />
        </div>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
