import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import React from 'react'
const inter = Inter({ subsets: ["latin"] });





export const metadata: Metadata = {
    title: "Green Market",
    description: "Generated by create next app",
  };


  const navbarProps = [
    {name:"Track My order",url:"/trackorder"},
    {name:"My Kart",url:"/mykart"},
    {name:"Be a Seller",url:"/beasellerat"},
    {name:"Profile",url:"/profile"},
  ]
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>){

    return(
        <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
            <body className={inter.className}>
              <div className="flex items-center justify-between mx-auto p-4 stick top-0 bg-slate-900 text-zinc-100">
                <div className="mx-auto">
                  <Image src={''} width={125} height={40} alt="" />

                </div>
                <div className='hidden sm:inline-flex gap-1 mx-auto'>
                <Input  type="search"placeholder="Search any Product"/>
                <Button>
                  Search
                </Button>
                </div>

                <ul className="hidden sm:inline-flex mx-auto gap-4 text-sm">
                  {
                    navbarProps?.map((items,data) =>(
                      <li key={data}>
                        <Link href={items.url}>
                          {items.name}
                        </Link>
                      </li>
                    ))
                  }
                </ul> 
                <UserButton />
              </div>
                {children}
            </body>
        </html>
    )
  }